services:

  catalogdb:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  basketdb:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  catalog.api:
    build:
      context: .
      dockerfile: ./src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb

  distributedcache:
    image: redis

volumes:
  postgres_catalog:
  postgres_basket: